version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: click_counter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d click_counter"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_USER=user
      - DB_HOST=db
      - DB_NAME=click_counter
      - DB_PASSWORD=password
      - DB_PORT=5432
      - USER_ID=${USER_ID}
      - CALL_ADMIN_ID=${CALL_ADMIN_ID}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./dist:/app/dist

volumes:
  pgdata: