version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: click_counter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_USER=user
      - DB_HOST=db
      - DB_NAME=click_counter
      - DB_PASSWORD=password
      - DB_PORT=5432
      - USER_ID=${USER_ID}
      - CALL_ADMIN_ID=${CALL_ADMIN_ID}
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

volumes:
  pgdata: